# Generated by Django 5.1.6 on 2025-02-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('scifi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror')], max_length=20)),
                ('episode_length', models.IntegerField(help_text='Average episode length in minutes')),
                ('total_episodes', models.IntegerField()),
                ('rating', models.FloatField(help_text='Rating from 1 to 10')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateTimeField(auto_now_add=True)),
                ('watched', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.netflixshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_study_hours', models.FloatField(default=4.0)),
                ('daily_sleep_hours', models.FloatField(default=8.0)),
                ('daily_leisure_hours', models.FloatField(default=2.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('scifi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror')], max_length=20)),
                ('weight', models.IntegerField(help_text='Preference weight from 1 to 10')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
